var searchData=
[
  ['c_20bindings_0',['2. C++ Bindings',['../db/d8b/md_docs_2mainpage.html#autotoc_md95',1,'']]],
  ['c_20extension_1',['2. Build the C++ Extension',['../d1/d66/getting_started.html#autotoc_md64',1,'']]],
  ['capabilities_2',['Core Capabilities',['../db/d8b/md_docs_2mainpage.html#autotoc_md90',1,'']]],
  ['characteristics_3',['Performance Characteristics',['../db/d8b/md_docs_2mainpage.html#autotoc_md108',1,'']]],
  ['classes_4',['Classes',['../db/d8b/md_docs_2mainpage.html#autotoc_md94',1,'1. Core Classes'],['../d2/d89/api_reference.html#autotoc_md0',1,'Core Classes']]],
  ['clone_20the_20repository_5',['1. Clone the Repository',['../d1/d66/getting_started.html#autotoc_md63',1,'']]],
  ['coefficient_20guidelines_6',['Drag Coefficient Guidelines',['../d0/dde/perturbations.html#autotoc_md139',1,'']]],
  ['collection_7',['Examples Collection',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md184',1,'']]],
  ['combined_20perturbations_8',['Combined Perturbations',['../d0/dde/perturbations.html#autotoc_md143',1,'']]],
  ['commands_20from_20java_9',['Executing Commands from Java',['../d1/d66/getting_started.html#autotoc_md76',1,'']]],
  ['common_20issues_10',['Common Issues',['../d1/d66/getting_started.html#autotoc_md83',1,'Common Issues'],['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md191',1,'Common Issues']]],
  ['comparative_20analysis_11',['4. Comparative Analysis',['../d1/d66/getting_started.html#autotoc_md72',1,'']]],
  ['compare_20with_20standard_20satellite_12',['Compare with standard satellite',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md54',1,'']]],
  ['compare_5forbital_5felements_13',['compare_orbital_elements()',['../d2/d89/api_reference.html#autotoc_md17',1,'']]],
  ['compare_5forbits_14',['compare_orbits()',['../d2/d89/api_reference.html#autotoc_md6',1,'']]],
  ['comparison_15',['Orbit Comparison',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#orbit-comparison',1,'']]],
  ['computational_20cost_16',['Computational Cost',['../d0/dde/perturbations.html#autotoc_md155',1,'']]],
  ['computational_20efficiency_17',['3. Computational Efficiency',['../d0/dde/perturbations.html#autotoc_md162',1,'']]],
  ['configuration_18',['Configuration',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md179',1,'⚙️ Configuration'],['../d0/dde/perturbations.html#autotoc_md118',1,'Configuration'],['../d0/dde/perturbations.html#autotoc_md125',1,'Configuration'],['../d0/dde/perturbations.html#autotoc_md130',1,'Configuration'],['../d0/dde/perturbations.html#autotoc_md138',1,'Configuration'],['../d2/d89/api_reference.html#autotoc_md33',1,'Perturbations Configuration'],['../d2/d89/api_reference.html#autotoc_md34',1,'Satellite Configuration']]],
  ['configuration_20management_19',['Configuration Management',['../d1/d66/getting_started.html#autotoc_md77',1,'']]],
  ['configurations_20',['Propagate with different configurations',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md55',1,'']]],
  ['configure_20satellite_20specific_20parameters_21',['Configure satellite-specific parameters',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md51',1,'']]],
  ['considerations_22',['Considerations',['../d0/dde/perturbations.html#autotoc_md147',1,'Mission-Specific Considerations'],['../d0/dde/perturbations.html#autotoc_md154',1,'Performance Considerations']]],
  ['constants_23',['Physical Constants',['../d2/d89/api_reference.html#autotoc_md37',1,'']]],
  ['constants_20and_20defaults_24',['Constants and Defaults',['../d2/d89/api_reference.html#autotoc_md36',1,'']]],
  ['constructor_25',['Constructor',['../d2/d89/api_reference.html#autotoc_md2',1,'Constructor'],['../d2/d89/api_reference.html#autotoc_md13',1,'Constructor'],['../d2/d89/api_reference.html#autotoc_md22',1,'Constructor']]],
  ['contributing_26',['🤝 Contributing',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md197',1,'']]],
  ['core_20capabilities_27',['Core Capabilities',['../db/d8b/md_docs_2mainpage.html#autotoc_md90',1,'']]],
  ['core_20classes_28',['Core Classes',['../db/d8b/md_docs_2mainpage.html#autotoc_md94',1,'1. Core Classes'],['../d2/d89/api_reference.html#autotoc_md0',1,'Core Classes']]],
  ['cost_29',['Computational Cost',['../d0/dde/perturbations.html#autotoc_md155',1,'']]],
  ['coverage_30',['Documentation Coverage',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md195',1,'']]],
  ['cubesat_20propagation_31',['CubeSat propagation',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md56',1,'']]],
  ['cubesat_20with_20large_20area_20to_20mass_20ratio_32',['Example: CubeSat with large area-to-mass ratio',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md52',1,'']]],
  ['custom_20documentation_20generation_33',['Custom Documentation Generation',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md187',1,'']]],
  ['custom_20perturbation_20parameters_34',['Custom Perturbation Parameters',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md50',1,'Custom Perturbation Parameters'],['../d0/dde/perturbations.html#autotoc_md152',1,'Custom Perturbation Parameters']]],
  ['customization_20options_35',['Customization Options',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md181',1,'']]]
];
