var searchData=
[
  ['satellite_0',['Compare with standard satellite',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md54',1,'']]],
  ['satellite_20configuration_1',['Satellite Configuration',['../d2/d89/api_reference.html#autotoc_md34',1,'']]],
  ['satellite_20display_2',['Multi-Satellite Display',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#multi-satellite',1,'']]],
  ['satellite_20propagation_3',['Standard satellite propagation',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md57',1,'']]],
  ['satellite_20specific_20parameters_4',['Configure satellite-specific parameters',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md51',1,'']]],
  ['satellite_20visualization_5',['5. Multiple Satellite Visualization',['../d1/d66/getting_started.html#autotoc_md73',1,'']]],
  ['scientific_20applications_6',['🔬 Scientific Applications',['../db/d8b/md_docs_2mainpage.html#autotoc_md102',1,'']]],
  ['selection_7',['1. Perturbation Selection',['../d0/dde/perturbations.html#autotoc_md160',1,'']]],
  ['set_5fperturbation_5fparameters_8',['set_perturbation_parameters()',['../d2/d89/api_reference.html#autotoc_md18',1,'']]],
  ['set_5fstatus_5fcallback_9',['set_status_callback()',['../d2/d89/api_reference.html#autotoc_md24',1,'']]],
  ['setting_20perturbation_20parameters_10',['Setting Perturbation Parameters',['../d1/d66/getting_started.html#autotoc_md78',1,'']]],
  ['setting_20up_20the_20bridge_11',['Setting up the Bridge',['../d1/d66/getting_started.html#autotoc_md75',1,'']]],
  ['settings_12',['Doxyfile Settings',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md180',1,'']]],
  ['shadow_20modeling_13',['Shadow Modeling',['../d0/dde/perturbations.html#autotoc_md133',1,'']]],
  ['simple_20propagation_20analysis_14',['Simple Propagation Analysis',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md47',1,'']]],
  ['simple_20tle_20visualization_15',['1. Simple TLE Visualization',['../d1/d66/getting_started.html#autotoc_md69',1,'']]],
  ['software_16',['Required Software',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md173',1,'']]],
  ['solar_20position_20model_17',['Solar Position Model',['../d0/dde/perturbations.html#autotoc_md124',1,'']]],
  ['solar_20radiation_20pressure_18',['3. Solar Radiation Pressure',['../d0/dde/perturbations.html#solar-radiation-pressure',1,'']]],
  ['specific_20considerations_19',['Mission-Specific Considerations',['../d0/dde/perturbations.html#autotoc_md147',1,'']]],
  ['specific_20parameters_20',['Configure satellite-specific parameters',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md51',1,'']]],
  ['specific_20references_21',['Perturbation-Specific References',['../d0/dde/perturbations.html#autotoc_md166',1,'']]],
  ['specifications_22',['🛠 Technical Specifications',['../db/d8b/md_docs_2mainpage.html#autotoc_md106',1,'']]],
  ['standard_20satellite_23',['Compare with standard satellite',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md54',1,'']]],
  ['standard_20satellite_20propagation_24',['Standard satellite propagation',['..//Users/evelynschuller/Desktop/Facultate/Master/An 1, sem 2/OOP/Project/ODETTE/Python_interface/Bindings_Python-interface-code/docs/examples/README.md#autotoc_md57',1,'']]],
  ['standards_25',['Documentation Standards',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md199',1,'']]],
  ['start_26',['Start',['../db/d8b/md_docs_2mainpage.html#autotoc_md97',1,'🎯 Quick Start'],['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md169',1,'🚀 Quick Start']]],
  ['started_27',['Getting Started',['../d1/d66/getting_started.html',1,'']]],
  ['statistics_20and_20metrics_28',['📊 Statistics and Metrics',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md194',1,'']]],
  ['steps_29',['Next Steps',['../d1/d66/getting_started.html#autotoc_md85',1,'']]],
  ['structure_30',['Structure',['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md168',1,'📁 Directory Structure'],['../db/d8b/md_docs_2mainpage.html#autotoc_md101',1,'📖 Documentation Structure'],['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md182',1,'📝 Documentation Structure']]],
  ['structures_31',['Data Structures',['../d2/d89/api_reference.html#autotoc_md31',1,'']]],
  ['success_20response_20format_20javaguibridge_32',['Success Response Format (JavaGUIBridge)',['../d2/d89/api_reference.html#autotoc_md44',1,'']]],
  ['sun_20synchronous_20orbits_33',['Sun-synchronous Orbits',['../d0/dde/perturbations.html#autotoc_md146',1,'']]],
  ['support_34',['Support',['../db/d8b/md_docs_2mainpage.html#autotoc_md112',1,'📞 Support'],['../dc/dae/md__r_e_a_d_m_e___d_o_c_u_m_e_n_t_a_t_i_o_n.html#autotoc_md201',1,'📞 Support']]],
  ['supporting_20modules_35',['3. Supporting Modules',['../db/d8b/md_docs_2mainpage.html#autotoc_md96',1,'']]],
  ['synchronous_20orbits_36',['Sun-synchronous Orbits',['../d0/dde/perturbations.html#autotoc_md146',1,'']]],
  ['system_20requirements_37',['System Requirements',['../d1/d66/getting_started.html#autotoc_md59',1,'System Requirements'],['../db/d8b/md_docs_2mainpage.html#autotoc_md107',1,'System Requirements']]]
];
